= Diplomarbeit EduCluster

// TODO gendern nicht vergessen!

[discrete]
=== Kurzfassung
Das Ziel der vorliegenden Diplomarbeit ist, ein System zu schaffen, um Lerngruppenbildung und damit verbundene Raumreservierungen effizienter zu gestalten.
Es soll eine funktionale Erweiterung von WebUntis in Verbindung mit Microsoft Teams geschaffen werden. Erzielt wird die Vereinheitlichung der genutzten Plattformen
zur Organisation von Lerninhalten und Datenaustausch. Zudem soll für die Schüler/innen eine Möglichkeit geschaffen werden, selbstständig Lernräume für Lerneinheiten zu buchen.

In der HTL Pinkafeld findet zurzeit die Raumreservierung exklusiv durch das Lehr- und Administrationspersonal statt. Darüber hinaus wird eine breite Palette an Plattformen
zur Datenbereitsstellung eingesetzt, wie beispielsweise WebUntis, LMS, Microsoft Teams, Google Docs und das Klassenlaufwerk. Diese Auswahl an Werkzeugen mündet in Unübersichtlichkeit
für die Schülerschaft beim Lernen. Dazu entsteht eine Schwierigkeit im Unterricht für Lehrkräfte im Anlegen und Organisieren der Klasse.

Hier kommt EduCluster ins Spiel. Mittels Clusterbildung ermöglicht die Web-Applikation eine einfache und übersichtliche Erstellung von Lerngruppen mitsamt Raumreservierung.
Ein Cluster stellt in EduCluster die Lerngruppe dar, welche nach der Erstellung Termine anlegen, Räume reservieren und über eine Suche von weiteren Mitschüler/innen gefunden werden kann.
Nutzende können beliebig solche Cluster erstellen oder ihnen beitreten. Durch das Erstellen können diese zukünftig als Clusteradministrierende handeln.
Zur Organisation dieses Clusters werden WebUntis zur Raumreservierung als auch Microsoft Teams zum Abhalten von Remote Lerneinheiten als auch Datenorganisation herangezogen, welche über die genannten Funktionalitäten
EduCluster zur Verfügung stehen.

[discrete]
=== Abstract
// TODO

[discrete]
=== Vorwort
// TODO

:sectnums:
:sectnumlevels: 6

== Einleitung
// TODO

include::projektantrag.adoc[]

// TODO Vorstudie

// TODO Evaluierung Lara

include::individueller-teil-raymond.adoc[]

// TODO Evaluierung Christoph

:sectnums!: